### PR TITLE
improve fedora-build

### PR DESCRIPTION
**Pull request by andyli**
* Install things to /usr/local instead of /usr, which is used for system packages installed with dnf.
 * Use dotnet 3.0.
   The README stated 3.0 is required. And there was indeed an error when I tried with 2.2.
 * Print command during execution. (set -x)
 * Stop when any command failed. (set -e)

### CODE REVIEW

**Comment by cerebrate** [comment]
Thanks for the pull request. I've added some of the changes in mainline, but I'd prefer not to have to support installation in /usr/local on a distribution I'm unfamiliar with. Genie's operation is already uncomfortably fragile in many ways.

The Fedora build script that directly installs locally was a user contribution I can't support, and ideally, I would prefer to support Fedora with a proper dnf package (why the Fedora build script is not mentioned in the README), just as I do with a deb package for Debian and its offshoots, and Arley Henostroza has contributed for Arch.

Would you perhaps be interested in turning fedora-build into a script to produce such a package?

**Comment by andyli** [comment]
About /usr/local, it's not a Fedora specific thing, but common to most Linux distros (including Debian, Fedora, openSUSE, Arch etc) following [Filesystem Hierarchy Standard (FHS)](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). Specifically, the page about /usr/local in FHS3 is https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html

**Comment by cerebrate** [comment]
Sure, I get that, but that's why I want this - certainly in any of my "official" distributions of genie - to be distributed as a deb/dnf/apk/rpm/etc. package and thus properly located under /usr .

I have no objection (in theory) to modifying the code such that it can be entirely installed under /usr/local, but while I'm still getting the wrinkles out and making regular changes in response to pre-launch WSL 2 changes, I'd prefer not to introduce another element to my cross-distro debugging issues.

...hm. Don't close this yet. Let me kick some thoughts around a bit.

**Comment by cerebrate** [comment]
Additional note: I don't want to simply stop hardcoding paths in genie to achieve that, though, since genie runs setuid, and as such using non-full paths when running subprocesses makes privilege escalation easy.

Granted, it's not, I suppose, quite the problem that it would be on non-WSL Linux since it's all running inside a single Windows-level user context anyway, and yet.

**Comment by andyli** [comment]
What about using config/build-time variables? It's what the autotools, cmake, dune (OCaml build tool) do to allow customizing installation prefix. I'm not familiar with the dotnet world but there should be something similar (compiler defines?).

**Comment by cerebrate** [comment]
I've updated the build process now, using make, so it can either generate an installation package (to go under /usr) or install genie locally (under /usr/local), changing hardcoded prefixes in the genie executable accordingly.

In some ways, unfortunately, this is a backward step from the old fedora-build script, because it leaves the dependencies to be installed manually rather than including them under `make install`, but I don't want to start including per-distro local-install targets; if I'm going to include something per-distro, I figure it should make the relevant package.

**Pull request closed without merging**
