### PR TITLE
Improve Arch packaging

### PR DESCRIPTION
**Pull request by xuanruiqi**
Rewrite parts of the PKGBUILD to conform with Arch Linux standards & common practices

### CODE REVIEW

**Comment by cerebrate** [comment]
A couple of questions:

 * these changes look like it might now be grabbing its own version of the last-released source from Github rather than using the access to the current source provided by the now-deleted binsrc/othersrc symlinks. Do I have that correct?
 * what does the sha256sums= line do? A fixed value here seems odd.

**Comment by xuanruiqi** [comment]
1. Yes, that's right and that's the Arch way to do things. In Arch, PKGBUILDs are supposed to be mostly stand-alone and runnable by any user, so not part of an entire software distribution. Other software packages use the same approach (see [here](https://github.com/boltgolt/howdy/blob/master/archlinux/howdy/PKGBUILD) for example).
2. That's the source checksum, used to verify the integrity of the source file. So it's supposed to be a fixed value.

**Comment by cerebrate** [comment]
1. Okay, that's going to require a change in my packaging workflow, but since I have similar updates planned for the other packagers, that's fine.
2. This, on the other hand - I can understand the reasoning when the packager is a separate entity from the developer, but here we're pulling the source code out of the same repo, so there shouldn't be any questions of its integrity, and I can live without the extra steps of issue-release/fix-checksum/push-packaging-script/package-release . Can we automate this?

**Comment by xuanruiqi** [comment]
Well, Arch provides a script called `updpkgsums` to automate exactly this. I believe it is part of the pacman software distribution, which is available on many distributions. On the other hand it's just a bash script, so it's easy to fetch this script.

**Comment by cerebrate** [comment]
Great! If you could add that in the appropriate place (Makefile?), that should be fine and I'll merge this. I run the Arch package builds in an Arch container, so no issues with script availability.

**Pull request merged**
