### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by mavaddat**
Based on the logo for a retro game hacking device by no-longer-existing company.

### CODE REVIEW

**Comment by cerebrate** [comment]
I don't want to use an offsite link. Can you add the logo itself to this pull request, in the docs folder?

**Comment by mavaddat** [comment]
> I don't want to use an offsite link. Can you add the logo itself to this pull request, in the docs folder?

Done. I had to remind myself how to upload files to GitHub using their interface.

**Comment by cerebrate** [comment]
Not sure where you put that, but I'm still not seeing the file in the repo; there's only the change to the readme in the commits.

**Comment by mavaddat** [comment]
Done. 🤦🏼‍♂️ I previously dragged the image into the `README.md`, which just uploads to the main github servers.

**Pull request merged**
