### PR TITLE
add Archlinux pkg & PKGBUILD

### PR DESCRIPTION
**Pull request by rayfalling**

### CODE REVIEW

**Comment by rayfalling** [comment]
I also update to dotnet5.0

**Comment by arlllk** [comment]
I don't think that the compiled binary should be included in the repository

**Comment by rayfalling** [comment]
Because I dont have permission to attach to release:(
Cloud some one move it to releases

**Comment by rayfalling** [comment]
I replace the build binary to a share link of my own cloud

**Comment by cerebrate** [comment]
As a side note on Arch support, one must credit the authors of the distribution for finding a way to break dhcp support inside containers.

For certain values of credit.

**Comment by cerebrate** [comment]
Can you jigger the PKGBUILD to include the man page and do the needful? That's probably the last thing, other than adding a release maintainer for the Arch version, that needs to be done before moving this to official.

**Comment by rayfalling** [comment]
Wait for me sometime, and I'll add it.(A little busy recent days)
I will try to add the package to archlinuxcn.
If thry refuse to add the package, I will build my own repo and add to it

**Comment by Axieum** [comment]
Hi @rayfalling, could you please comment on how I should go about installing `dotnet-sdk>=5.0` on Arch? I can only find latest of `3.1.8` on both community and AUR.

**Comment by rayfalling** [comment]
@Axieum AUR contains the package, link here: [https://aur.archlinux.org/packages/dotnet-sdk-bin/](https://aur.archlinux.org/packages/dotnet-sdk-bin/)
also you can find it in archlinuxcn repo

**Comment by Axieum** [comment]
Awesome, thanks for that! I've almost got it building, although I can't seem to make the package, and no matter what I do with symbolic links, etc. it doesn't work. Any thoughts?

image

**Comment by rayfalling** [comment]
You should copy the PKGBUILD to a temp dir, such as `/tmp/build_pkg` then `cd /tmp/build_pkg`.
Pacman has its own package toolchain, so you should excute `makepkg` in temp directory with PKGBUILD.
After its finish building, excute `sudo pacman -U xxxx.pkg.tar.gz`, xxxx.pkg.tar.gz is what makepkg output.

**Comment by Axieum** [comment]
Perfect, clearing out the directory worked, thanks 😄

**Pull request merged**
