### PR TITLE
genie worked with Fedora Remix for WSL.

### PR DESCRIPTION
**Pull request by tomoyan596**
Since error CS0121 occurred in the build, it was corrected.
> $ cd genie/genie
> $ dotnet publish -r linux-x64 --self-contained false
> Program.cs(75,50): error CS0121: The call is ambiguous between the following methods or properties: 'CommandHandler.Create<T>(Func<T, int>)' and 'CommandHandler.Create<T>(Func<T, Task<int>>)' [/mnt/c/Users/tomoyan/genie/genie/genie.csproj]
> Program.cs(80,52): error CS0121: The call is ambiguous between the following methods or properties: 'CommandHandler.Create<T>(Func<T, int>)' and 'CommandHandler.Create<T>(Func<T, Task<int>>)' [/mnt/c/Users/tomoyan/genie/genie/genie.csproj]
> Program.cs(87,47): error CS0121: The call is ambiguous between the following methods or properties: 'CommandHandler.Create<T>(Func<T, int>)' and 'CommandHandler.Create<T>(Func<T, Task<int>>)' [/mnt/c/Users/tomoyan/genie/genie/genie.csproj]
> Program.cs(99,46): error CS0121: The call is ambiguous between the following methods or properties: 'CommandHandler.Create<T1, T2>(Func<T1, T2, int>)' and 'CommandHandler.Create<T1, T2>(Func<T1, T2, Task<int>>)' [/mnt/c/Users/tomoyan/genie/genie/genie.csproj]

First of all, I created a script that can be installed on Fedora Remix.
> $ cd ~
> $ git clone <genie-systemd repository>
> $ cd genie
> $ ./fedora-build

If you build with the 9p file system, the executable will be corrupted.
When building with /mnt/c, the following error occurred and it did not work.
> $ genie/bin/Debug/netcoreapp2.2/linux-x64/publish/genie
> This executable is not bound to a managed DLL to execute. The binding value is: 'c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2'
> A fatal error was encountered. This executable was not bound to load a managed DLL.

You can avoid this by doing a cd ~ and then building with git clone.

This works well.
> bash
> $ genie -s

But for some reason this doesn't work.
> wsl genie -s
> A fatal error occurred, the required library libhostfxr.so could not be found.
> If this is a self-contained application, that library should exist in [/usr/bin/].
> If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.

https://www.tomoyan.net/windows/wsl#genie-systemd_%E3%81%AE_fork

### CODE REVIEW

**Comment by tomoyan596** [comment]
The fedora rpm spec file will be created later.

**Comment by cerebrate** [comment]
Thanks muchly for this.

Regarding the issue with `wsl genie -s` not functioning, I think that might be the same issue as the one Arch has, per #9 (the libhostxfr error is mentioned in the Reddit link in that issue). Presumably the bash startup files on Fedora Remix set DOTNET_ROOT and so let it work.

**Comment by tomoyan596** [comment]
Thank you for merging immediately!
Since Fedora adopted systemd early, the impact of not using systemd is significant.
Many thanks to genie-systemd!
Thank you for the wonderful work!

The behavior of the wsl command seems a little tricky.
It seems that /etc/profile.d/* is not executed when bash is executed from wsl command.
The cause is unknown.
> bash
$ env
SHELL=/bin/bash
LIBGL_ALWAYS_INDIRECT=1
HISTCONTROL=ignoredups
WSL_DISTRO_NAME=fedoraremix
HISTSIZE=1000
HOSTNAME=Cmon-wsl
DOTNET_ROOT=/usr/lib64/dotnet
NO_AT_BRIDGE=1
NAME=Cmon
PWD=/mnt/c/Users/tomoyan
LOGNAME=tomoyan
HOME=/home/tomoyan
LANG=en_US.UTF-8
...

When executed from the wsl command.
> wsl bash -c env
SHELL=/bin/bash
WSL_DISTRO_NAME=fedoraremix
NAME=Cmon
PWD=/mnt/c/Users/tomoyan
LOGNAME=tomoyan
_=/usr/bin/env
HOME=/home/tomoyan
LANG=en_US.UTF-8
...

DOTNET_ROOT is set by /etc/profile.d/dotnet.sh.
> $ cat /etc/profile.d/dotnet.sh
> *#* Set location for AppHost lookup
> [ -z "$DOTNET_ROOT" ] && export DOTNET_ROOT=/usr/lib64/dotnet
> 
> *#* Add dotnet tools directory to PATH
> DOTNET_TOOLS_PATH="$HOME/.dotnet/tools"
> case "$PATH" in
>    `*`"$DOTNET_TOOLS_PATH"* ) true ;;
>    `*` ) PATH="$PATH:$DOTNET_TOOLS_PATH" ;;
> esac

Then, when you run genie -s, /etc/hosts seems to be different from the one generated by Microsoft's /init.
> $ cat /etc/hosts
> *#* This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
> *#* [network]
> *#* generateHosts = false
> 127.0.0.1       localhost
> 127.0.1.1       Cmon.localdomain        Cmon
> 127.0.0.1       monsters-g.local
> 
> *#* The following lines are desirable for IPv6 capable hosts
> ::1     ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> ff00::0 ip6-mcastprefix
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters

When you run genie -s ...
The host name Cmon is changed to Cmon-wsl.
> $ genie  -s
> Deleted Cmon
> Cmon-wsl not found in /etc/hosts
> Added Cmon-wsl -> 127.0.0.1 (On)
> $ cat /etc/hosts
> 127.0.0.1 localhost Cmon-wsl monsters-g.local
> 127.0.1.1 Cmon.localdomain
> ::1 ip6-localhost ip6-loopback
> fe00:: ip6-localnet
> ff00:: ip6-mcastprefix
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters

But so far there is no significant impact ...

**Comment by tomoyan596** [comment]
By the way, this is convenient.
/etc/profile.d/genie.sh
if [ "`ps -eo pid,lstart,cmd | grep systemd | grep -v -e grep -e systemd- | sort -n -k2 | awk 'NR==1 { print $1 }'`" != "1" ]; then
  genie -s
fi

**Comment by arlllk** [comment]
> By the way, this is convenient.
> /etc/profile.d/genie.sh
> if [ "`ps -eo pid,lstart,cmd | grep systemd | grep -v -e grep -e systemd- | sort -n -k2 | awk 'NR==1 { print $1 }'`" != "1" ]; then
> genie -s
> fi

This would be great addition to the wiki

**Comment by cerebrate** [comment]
On the former - the issue is that when you run a shell as a command using `wsl`, it runs it as any other command, so it doesn't know that it's effectively a login shell (for example, `echo $0` will return `bash` not `-bash`) and doesn't execute the various only-for-login-shells scripts.

If you try starting it with `wsl bash -l`, which forces it to be a login shell, it should execute `/etc/profile.d/*` et. al. properly.

**Comment by cerebrate** [comment]
On the latter - the change in hostname (and editing the hosts file accordingly) is actually a genie feature. With WSL 2 using, currently, a different IP address from the Windows host, having it share the same hostname can cause various issues; for one thing, you can't access the network interface of the Windows host (not localhost, the physical or virtual NIC) by name, some utilities get confused by the existence of an apparent duplicate host with the same hostname, and so forth.

I've had some glitchiness result from this, so to avoid network problems inside the bottle, genie creates a temporary hostname file suffixed `-wsl` at /run/hostname and mounts this over /etc/hostname, and rewrites /etc/hosts to match.

**Pull request merged**
